(ql:quickload :alexandria)

(defun smallest-multiple (limit)
  (let ((values (alexandria:iota (1- limit) :start 2 :step 1))
	(multipliers '()))
    (format t "Values ~a" values)
    (labels ((more (values multipliers)
	       (if (null values)
		   (print (reduce #'* multipliers))
                   (let ((div (car values))
			 (rest (cdr values)))
		     (push div multipliers)
		     (more (mapcar (lambda (x)
				     (if (zerop (mod x div))
				     	 (/ x div)
				     	 x))
				   rest) multipliers)))))
      (more values multipliers))))

(smallest-multiple 20)
